services:
  db-sql:
    container_name: parkour-db-sql
    image: postgres:latest
    env_file: ./.env
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678